name: Python-lint

# Run this workflow every time on push
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  python-lint:
    # Name the Job
    name: Run black python linter checks
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.8]

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Lint with black
      run: |
        $CONDA/bin/conda install -c conda-forge black==19.10b0
        # stop the build if there are Python syntax errors or undefined names
        $CONDA/bin/black --check minian
